version: '3.7'

volumes:
  db_data:

x-shared_environment: &shared_environment
  DATABASE_HOST: $DATABASE_HOST
  DATABASE_PORT: $DATABASE_PORT
  DATABASE_NAME: $DATABASE_NAME
  DATABASE_USERNAME: $DATABASE_USERNAME
  DATABASE_PASSWORD: $DATABASE_PASSWORD
  
services:
  app:
    build:
      context: ./app
    environment:
      <<: *shared_environment
    depends_on:
      - db
    ports:
      - '8080:8080'
    command: ["swift", "run", "App", "serve", "--hostname", "0.0.0.0", "--port", "8080", "--auto-migrate"]
  db:
    image: postgres:16-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - '5432:5432'

    volumes:
      - db_data:/var/lib/postgresql/data/pgdata